### ISSUE TITLE
Not working with UWP SDK 10240.

### ISSUE THREAD

**Issue by karabasosman** [davidezordan/playready_adaptive_UWP#1]
Hi ,

I tried your repo on Windows 10 RTM, but "Error : unsupported type" occured. Did you try on RTM ?

Best regards,
Osman

**Comment by davidezordan** [comment]
Fixed

**Comment by karabasosman** [comment]
Hi,

Your sample is not working if Hardware DRM is not supported in the device. Update your project or readme.md

For further information : 
https://msdn.microsoft.com/en-us/library/windows/apps/xaml/dn705883.aspx

Best regards,
Osman

**Comment by davidezordan** [comment]
Thank you Osman.
I've updated the readme.md

Davide
